version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: